server:
  port: 65000

spring:
  application:
    name: hello-service
  main:
    web-application-type: reactive

info:
  app:
    name: ${spring.application.name}
    description: "Pulse Sprint 0 hello-service"
    version: "1.0.0-SNAPSHOT"

# Log format
logging:
  pattern:
    level: "%5p [${spring.application.name:app},%X{traceId}]"
  level:
    root: INFO
    com.zeabay.common: DEBUG
