services:
  postgres:
    image: postgres:16-alpine
    container_name: pulse-postgres
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse
    ports:
      - "5432:5432"
    volumes:
      - pulse_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pulse-redis
    ports:
      - "6379:6379"

volumes:
  pulse_pg:
