services:
  postgres:
    image: postgres:16-alpine
    container_name: pulse-postgres
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse
    ports:
      - "5432:5432"
    volumes:
      - pulse_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pulse-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    container_name: pulse-kafka
    ports:
      # host -> kafka
      - "9092:9092"
    environment:
      # KRaft single-node
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # listeners (host:9092) + (docker network:29092)
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # dev convenience
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - pulse_kafka:/bitnami/kafka

volumes:
  pulse_pg:
  pulse_kafka:
